using System.Collections.Generic;
using TMPro;
using UnityEngine;

/// <summary>
/// Fonts, shape sprites and icons for the Kurye Defteri UI.
/// Generated by Tools > Delivery Game > Cozy UI > Generate Assets, loaded from Resources/CozyUI/CozyAssets.
/// </summary>
[CreateAssetMenu(menuName = "Delivery Game/Cozy UI Assets", fileName = "CozyAssets")]
public class CozyAssets : ScriptableObject
{
    public const string ResourcePath = "CozyUI/CozyAssets";

    [System.Serializable]
    public class NamedSprite
    {
        public string name;
        public Sprite sprite;
    }

    [Header("Fonts")]
    public TMP_FontAsset display;      // Fredoka SemiBold: headings, buttons
    public TMP_FontAsset displayBold;  // Fredoka Bold: big numbers, logo, key caps
    public TMP_FontAsset body;         // Nunito SemiBold: running text
    public TMP_FontAsset bodyBold;     // Nunito ExtraBold: labels, chips
    public TMP_FontAsset mono;         // Courier Prime Bold: tracking codes, receipt lines

    [Header("Shapes (white, tinted by Image.color)")]
    public Sprite round16;
    public Sprite round32;
    public Sprite round64;
    public Sprite circle;
    public Sprite softShadow;
    public Sprite dash;
    public Sprite lined;
    public Sprite zigzag;

    [Header("Icons (white, 128px)")]
    public List<NamedSprite> icons = new List<NamedSprite>();

    private static CozyAssets cached;
    private Dictionary<string, Sprite> iconLookup;

    public static CozyAssets Instance
    {
        get
        {
            if (cached == null) cached = Resources.Load<CozyAssets>(ResourcePath);
            return cached;
        }
    }

    public Sprite Icon(string iconName)
    {
        if (string.IsNullOrEmpty(iconName)) return null;
        if (iconLookup == null || iconLookup.Count != icons.Count)
        {
            iconLookup = new Dictionary<string, Sprite>();
            foreach (NamedSprite ns in icons)
            {
                if (ns != null && !string.IsNullOrEmpty(ns.name)) iconLookup[ns.name] = ns.sprite;
            }
        }
        iconLookup.TryGetValue(iconName, out Sprite s);
        return s;
    }

    /// <summary>Picks the rounded sprite and pixelsPerUnitMultiplier that draw the requested corner radius.</summary>
    public Sprite RoundFor(float radius, out float pixelsPerUnitMultiplier)
    {
        Sprite s;
        float spriteRadius;
        if (radius <= 16f) { s = round16; spriteRadius = 16f; }
        else if (radius <= 32f) { s = round32; spriteRadius = 32f; }
        else { s = round64; spriteRadius = 64f; }
        pixelsPerUnitMultiplier = spriteRadius / Mathf.Max(1f, radius);
        return s;
    }
}
