// <auto-generated> from tutorial_texts.js. Turkish fallbacks used when localization files are missing a key.
using System.Collections.Generic;

public static class TutorialTexts
{
    private static readonly Dictionary<string, string> Tr = new Dictionary<string, string>
    {
        { "tut_label", "Rehber" },
        { "tut_skip", "[Enter] ile geç" },
        { "tut_btn_ok", "Anladım" },
        { "tut_guide_title", "Rehber" },
        { "tut_guide_sub", "İstediğin ipucunu yeniden izleyebilirsin." },
        { "tut_guide_seen", "Görüldü" },
        { "tut_guide_new", "Yeni" },
        { "tut_guide_close", "[F1] ile kapat" },
        { "tut_pages", "{0} sayfa" },
        { "tut_pickup_title", "Günün kargosu hazır" },
        { "tut_pickup_p1", "Depodaki koliye bak ve {Interact} ile eline al." },
        { "tut_pickup_sub", "İlk kargoyu alırken" },
        { "tut_clue_title", "Teslim noktasını bul" },
        { "tut_clue_p1", "Kargo, adresindeki <b>teslim noktasına</b> bırakılmalı. Sağdaki etikette yazan <b>adres tarifini</b> oku, o evin posta kutusunu bul." },
        { "tut_clue_p2_title", "Uzaksa araca bin" },
        { "tut_clue_p2", "Adres uzaksa {Vehicle} ile araca bin. Koliyi bagaja koyup taşıyabilirsin." },
        { "tut_clue_sub", "Kolu eline alınca" },
        { "tut_vehicle_title", "Araç kullanımı" },
        { "tut_vehicle_p1", "{MoveForward} {MoveBackward}   Gaz ve fren\n{MoveLeft} {MoveRight}   Direksiyon\n{Jump}   El freni\n{Camera}   Kamera değiştir" },
        { "tut_vehicle_p2_title", "Bagaj kullanımı" },
        { "tut_vehicle_p2", "Koliyi arkaya taşı: {Interact} ile bagaj kapağını aç, {DropCargo} ile içine yavaşça bırak." },
        { "tut_vehicle_sub", "İlk kez araca binince" },
        { "tut_first_delivery_title", "İlk teslimat tamam!" },
        { "tut_first_delivery_p1", "Bütün kargoları teslim edince {Tablet} ile Kurye Defteri'ni aç ve <b>Vardiyayı bitir</b>'e bas. Sonucu gün sonu fişinde görürsün." },
        { "tut_first_delivery_sub", "İlk teslimattan sonra" },
        { "tut_day_end_title", "Gün sonu fişin hazır" },
        { "tut_day_end_subtitle", "Kazancın şöyle hesaplanır:" },
        { "tut_day_end_r1", "Doğru teslim ettiğin kargolar sana <b>ödül</b> kazandırır." },
        { "tut_day_end_r2", "Yanlış adrese bıraktığın ya da kırdığın kargolardan <b>ceza</b> kesilir." },
        { "tut_day_end_r3", "Günlük <b>şube kirası</b> da hesaba dahil edilir ve kazancından düşülür." },
        { "tut_day_end_sub", "İlk gün sonunda" },
        { "tut_branch_upgrade_title", "Şubeni yükseltebilirsin!" },
        { "tut_branch_upgrade_p1", "Kazandığın para seviye 2 için yetti. Şube terminaline gidip {Interact} ile aç. Her seviyenin yenilikleri terminal panelinde yazıyor; yükseltmeyi oradan yaparsın." },
        { "tut_branch_upgrade_sub", "Yükseltmeye paran yetince" },
        { "tut_low_fuel_title", "Benzin bitmek üzere" },
        { "tut_low_fuel_p1", "Yakıtın %20'nin altına düştü. Benzin bitince araç çalışmaz; düzenli doldurmayı unutma. En yakın benzin istasyonuna git." },
        { "tut_low_fuel_sub", "Yakıt %20'nin altına inince" },
        { "tut_low_condition_title", "Aracın hırpalandı" },
        { "tut_low_condition_p1", "Araç durumu %30'un altına düştü. Onarmazsan araç sorunlu çalışır. Oto servise uğrayıp aracını onar." },
        { "tut_low_condition_sub", "Araç durumu %30'un altına inince" },
    };

    public static string Fallback(string key)
    {
        return Tr.TryGetValue(key, out string value) ? value : key;
    }

    /// <summary>Localized text with the built-in Turkish text as fallback.</summary>
    public static string Get(string key)
    {
        return LocalizationManager.Get(key, Fallback(key));
    }
}
